const Questions = {
  EntraID: [
    { q: "Three types of user accounts", a: "1) Cloud<br>2) Directory synchronized<br>3) Guest user", tag: 0 },
    { q: "Three templates to create cloud user", a: "1) Create user<br>2) Invite user<br>3) Create B2C user", tag: 0 },
    { q: "Who can preset data for the cloud user?", a: "Global administrator or User administrator", tag: 0 },
    { q: "Which two names does the user account have?", a: "1) Display name - Viktor Hulei<br>2) User principal name vikhulei@fixitfast.com", tag: 0 },
    { q: "How many days before cloud user account is permanently deleted?", a: "30 days", tag: 0 },
    { q: "How to view errors when creating bulk accounts?", a: "Bulk operation results page in the Azure portal", tag: 0 },
    { q: "What are security group account used for?", a: "To manage member and computer access to shared resources", tag: 0 },
    { q: "What are Microsoft 365 group accounts used for?", a: "To provide access to shared mailboxes, calendars, files, SharePoint sites and more<br>Access for guest users", tag: 0 },
    { q: "Who can implement security groups and MS365 groups?", a: "Security groups - Microsoft Entra admin<br>MS365 - normal users and Microsoft Entra admins", tag: 0 },
    { q: "What are three ways to add members to the groups?", a: "Assigned - add specific users<br>Dynamic - depends on member's attribute<br>Dynamic device (only for security group) - depends on the device's attribute", tag: 0 },
    { q: "What is admin unit used for?<br>What can you use to manage admin units?<br>Who can manage AUs?", a: "Admin units are used to assign management permissions to the users<br>Azure portal, PowerShell, Graph API, Microsoft 365 admin center can be used<br> Global Admin or Privileged Role Admin can manage AUs", tag: 0 },
    { q: "	What is:<br>Identity<br>Account<br>Microsoft Entra account<br>Azure Tenant<br>Azure subscription	", a: "	Identity - object with username and password<br>Account - identity that has data<br>Entra account is created with Entra ID or MS365<br>Tenant represents organization<br>Subscription is used to pay for services	", tag: 0 },
    { q: "	What is:<br>Identity<br>Account<br>Microsoft Entra account<br>Azure Tenant<br>Azure subscription	", a: "	Identity - object with username and password<br>Account - identity that has data<br>Entra account is created with Entra ID or MS365<br>Tenant represents organization<br>Subscription is used to pay for services	", tag: 0 },
    { q: "	ADDS vs Entra: communication protocols, federation services, structure, what is managed	", a: "	Protocols - no Kerberos, HTTPS (SAML, WS-F, OAuth)<br>Federation services and 3rd party (Facebook...)<br>Flat structure - no OUs and GPOs<br>Only users, groups and policies are managed	", tag: 0 },
    { q: "	Three Microsoft Entra editions	", a: "	Free - 500 th. objects, SSO, Core Identity & Access management, B2B colaboration<br>P1 - Everything else except Identity Protection and Identity Governance<br>P2 - Everything	", tag: 0 },
    { q: "	Which account is used to manage SSPR feature?<br>What are the three options to apply for users who can reset passwords?	", a: "	Global administrator account<br>None, Selected, All	", tag: 0 },
  ],
  Subscriptions: [
    { q: "	How many regions in how many countries are there?<br>What is the minimal distance between datacenters?<br>Which regions are paired and are not in the same geography?	", a: "	60 regions in 140 countries<br>At least 300 miles of separation is prefered<br>Brazil South and Singapore are paired but are not in the same geography	", tag: 0 },
    { q: "	Four ways to obtain Azure subscription	", a: "	Enterprise agreement<br>Microsoft reseller<br>Microsoft partner<br>Personal free account	", tag: 0 },
    { q: "	Four most popular types of Azure subscription	", a: "	Free, Pay-As-You-Go, Enterprise Agreement, and Student	", tag: 0 },
    { q: "	Explain Microsoft Cost Management analysis	", a: "	Microsoft Cost Management cost analysis features explores and analyses your organizational costs. You can monitor accumulated costs over time to estimate monthly, quarterly, or even yearly cost trends against a budget	", tag: 0 },
    { q: "	What are tags used for? What are two parts of a tag? What is the maximum number of tags per resource?",	a:	"Tags are useful for sorting, searching, managing, and doing analysis on your resources.<br>Name/value pair<br>50	", tag: 0 },
    { q: "	Explain Reservations as cost saving option. How much can you save?	", a: "	Reservation is saving money by paying ahead. Can save up to 72%	", tag: 0 },
    { q: "	What is Azure Credit?<br>How can you save with Azure regions?<br>What can you use to provide estimates for all areas, including compute, networking, storage, web?	", a: "	Use the monthly credit benefit to develop, test, and experiment with new solutions on Azure<br>Pricing can vary from one region to another<br>Pricing calculator	", tag: 0 },
  ],
  AzurePolicy: [
    { q: "	What is management group?<br>How deep is the management group tree?	", a: "	It is a container to manage access, policy, and compliance across the subscriptions.<br>A management group tree can support up to six levels of depth	", tag: 0 },
    { q: "	What is used to create management groups?<br>Which two properties are set when creating management group?	", a: "	 Azure portal, PowerShell, or the Azure CLI with the Azure Policy<br>Management group ID and management group display name	", tag: 0 },
    { q: "	What is Azure Policy?	", a: "	Azure Policy is a service in Azure that you can use to create, assign, and manage policies. You can use policies to enforce rules on your resources to meet corporate compliance standards	", tag: 0 },
    { q: "	Four things Azure policies can be used for	", a: "	Deployable resources (specify the set of virtual machine SKUs)<br>Location restrictions<br>Rules enforcement (enforce a required tag on resources)<br>Inventory audits (use Azure Backup service and run inventory audits)	", tag: 0 },
    { q: "	4 steps to create Azure policy	", a: "	Step 1: Create policy definitions; Step 2: Create an initiative definition; Step 3: Scope the initiative definition; Step 4: Determine compliance	", tag: 0 },
    { q: "	Two examples of built-in policy definitions	", a: "	Allowed virtual machine size SKUs: Specify a set of VM size SKUs (compute cat.)<br>Allowed locations: Restrict the locations (General cat.)	", tag: 0 },
    { q: "	Two examples of built-in initiative definitions	", a: "	Audit machines with insecure password security settings (Guest configuration cat.)<br>Configure Azure Defender to be enabled on SQL servers (SQL cat.)	", tag: 0 },
    { q: "	Which two option have to be selected when determining the initiative definition scope?	", a: "	1) Subscription 2) Resource group	", tag: 0 },
    { q: "	What do we use Compliance feature for?	", a: "	We use the Compliance feature to look for non-compliant initiatives, policies, and resources	", tag: 0 },
  ],
  RBAC: [
    {q: "	What is the definition and examples of security principals?<br>What are some built-in role definitions?How many of them are there?	", a: "	Object that requests access to resources. E.g. - user, group, service principal, managed identity<br>Some built-in role definitions: Reader, Contributor, Owner, User Access Administrator. Over 100 roles	", tag: 0},
    {q: "	What is an example of a role assignment?<br>What is the definition and examples of the scopes?	", a: "	Assign the User Access Administrator role to an admin group scoped to a management group<br>Boundary where the access is granted - management group, subscription, resource group, resource	", tag: 0},
    {q: "	Four sets of RBAC permissions in JSON file<br>What is the highest built-in role?	", a: "	Actions, NotActions, DataActions (how data can be changed or used), AssignableScopes<br>Owner	", tag: 0},
    {q: "	What is Actions permission for Reader role?<br>What is NotActions permission for Contributor?	", a: "	/*/read<br>- Microsoft.Authorization/*/Delete, - Microsoft.Authorization/*/Write	", tag: 0},
    {q: "	Which two parts are composing effective permissions?	", a: "	Permissions for the requestor's roles + permissions for the role asigned to the resource	", tag: 0},
    {q: "	Azure RBAC roles vs Microsoft Entra admin roles	", a: "	Entra admin roles are used to manage resources in Microsoft Entra ID, such as users, groups, and domains<br>Azure RBAC roles provide more granular access management for Azure resources	", tag: 0},
    {q: "	Describe the roles of Owner, Contributor, Reader and User Access Administrator	", a: "	Owner - full access<br>Contributor - can create, cannot delete/modify, cannot grant access to others<br>Reader - can view existing resources<br>User Access - can manage user access to resources	", tag: 0},
  ],

};

export default Questions;